version: '3'

tasks:
  setup:
    desc: 'Setup local env.'
    cmds:
      - aqua i
      - bun install
      - lefthook install
  zenn:
    description: 'Handle Zenn CLI.'
    cmds:
      - bunx zenn-cli {{.CLI_ARGS}}
  textlint:
    description: 'Check rules for articles and books by textlint.'
    cmds:
      - bunx textlint {{.CLI_ARGS}}
