version: '3'

tasks:
  setup:
    desc: 'Setup local env.'
    cmds:
      - aqua i
      - bun install
      - lefthook install
  setup-ci:
    desc: 'Setup for CI env.'
    cmds:
      - bun install
  zenn:
    desc: 'Handle Zenn CLI.'
    cmds:
      - bunx zenn-cli {{.CLI_ARGS}}
  textlint:
    desc: 'Check rules for articles and books by textlint.'
    cmds:
      - bunx textlint {{.CLI_ARGS}}
