title: "Sphinxでもプレゼンテーション"
summary: |-
  Python製ドキュメンテーションビルダーSphinxを用いて、HTMLプレゼンテーションを作成してみませんか？

topics:
  - sphinx
  - revealjs
published: false
price: 0
chapters:
  - introduction
  - about-sphinx-revealjs
  - getting-started
  - use-sphinx-extensions
  - deployment-github-pages
  - conclusion