title: "Sphinxでもプレゼンテーション"
summary: |-
  Python製ドキュメンテーションビルダーSphinxを用いて、プレゼンテーションをしてみませんか？
  この本は、Sphinxの拡張を使ってreStructuredTextからReveal.jsのプレゼンテーションを生成するハンドブックです。
topics:
  - sphinx
  - revealjs
published: true
price: 0
chapters:
  - introduction
  - about-sphinx-revealjs
  - getting-started
  - use-plugins-and-extensions
  - deployment-github-pages
  - conclusion
